#!/usr/bin/env bash

# Inputs
# $1: Directory path
# $2: Temp file containing results in format: url|width|height

DIR="$1"
RESULTS_FILE="$2"

RULES_DIR="$DIR/.agent/rules"
RULES_FILE="$RULES_DIR/image_dimensions.md"

mkdir -p "$RULES_DIR"

cat << 'EOF' > "$RULES_FILE"
# Codebase Remote Images

> [!NOTE]
> This file is strictly auto-generated by `imgstat`.
> It maps remote image URLs found in the codebase to their exact physical dimensions.
> AI assistants should use this dictionary when asked about layout constraints, native sizes, or aspect ratios of referenced images.

| Documented URL | Detected Size (W x H) |
|---|---|
EOF

while IFS='|' read -r url w h; do
  echo "| \`$url\` | **${w}x${h}** |" >> "$RULES_FILE"
done < "$RESULTS_FILE"

echo "Wrote generic rules to: $RULES_FILE"
