#!/usr/bin/env bash

# Inputs
# $1: Directory path
# $2: Temp file containing results in format: url|width|height

DIR="$1"
RESULTS_FILE="$2"
RULES_FILE="$DIR/CLAUDE.md"

TEMP_BLOCK=$(mktemp)

cat << 'EOF' > "$TEMP_BLOCK"
## image dimensions

generated by imgstat. run `npx imgstat` to regenerate.

never guess image sizes. use the table below.

| file | width | height |
|------|-------|--------|
EOF

while IFS='|' read -r url w h; do
  echo "| $url | $w | $h |" >> "$TEMP_BLOCK"
done < "$RESULTS_FILE"

# Appending / Replacing logic
if [[ -f "$RULES_FILE" ]] && grep -q "## image dimensions" "$RULES_FILE"; then
  # Block exists. Let's delete it.
  sed -i.bak '/## image dimensions/,$d' "$RULES_FILE"
  rm -f "${RULES_FILE}.bak"
fi

if [[ -f "$RULES_FILE" ]]; then
  echo "" >> "$RULES_FILE"
fi

cat "$TEMP_BLOCK" >> "$RULES_FILE"
rm -f "$TEMP_BLOCK"

echo "Wrote claude code rules to: $RULES_FILE"
