#!/usr/bin/env bash

# Inputs
# $1: Directory path
# $2: Temp file containing results in format: url|width|height

DIR="$1"
RESULTS_FILE="$2"
RULES_FILE="$DIR/.windsurfrules"

TEMP_BLOCK=$(mktemp)

cat << 'EOF' > "$TEMP_BLOCK"
# imgstat — image dimensions
# generated by imgstat. do not edit this block manually.
# run `npx imgstat` to regenerate.

when working with images, never guess dimensions. refer to the table below.

| file | width | height |
|------|-------|--------|
EOF

while IFS='|' read -r url w h; do
  echo "| $url | $w | $h |" >> "$TEMP_BLOCK"
done < "$RESULTS_FILE"

# Appending / Replacing logic
if [[ -f "$RULES_FILE" ]] && grep -q "# imgstat — image dimensions" "$RULES_FILE"; then
  # Block exists, let's remove it and everything after it (assuming block is at the bottom)
  # Actually, safer to sed replace everything from the start tag until the end of file.
  # But the instructions say "append a clearly delimited block at the bottom".
  # If it exists, replace only that block.
  # Let's assume the block starts at "# imgstat — image dimensions" and continues to EOF.
  sed -i.bak '/# imgstat — image dimensions/,$d' "$RULES_FILE"
  rm -f "${RULES_FILE}.bak"
fi

if [[ -f "$RULES_FILE" ]]; then
  # Ensure there's a newline before appending
  echo "" >> "$RULES_FILE"
fi

cat "$TEMP_BLOCK" >> "$RULES_FILE"
rm -f "$TEMP_BLOCK"

echo "Wrote windsurf rules to: $RULES_FILE"
